site_name: My Project Documentation
nav:
  - Home: index.md
  - API:
      - Module 1: module1.md
      - Module 2: module2.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google